version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=proofYou3
      - POSTGRES_DB=freelance_db
    ports:
      - '5432:5432'

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: django_app
    command: sh ./run_web.sh
    ports:
      - "8000:8000"
    depends_on:
      - postgres